### ISSUE TITLE
Exception on MsHidStream.WriteHidReport

### ISSUE THREAD

**Issue by mwettach** [FrozenCow/wiidevicelibrary#3]
Hello,

i have some problems to run your library on my system (Windows 8.1)

First, i tried to run the Examples project with the MsBluetoothProvider but the wiimote wasn't found.

Than i installed BlueSoleil. Now it finds the wiimote, but it runs into an exception in MsHidStream.WriteHidReport 

An unhandled exception of type 'System.IO.IOException' occurred in mscorlib.dll
Additional information: The parameter is incorrect.

I found some information in the other issue about 64 vs 32 bit but nothing solves my problem.

Any ideas?

**Comment by FrozenCow** [comment]
Could you post the full exception and stack trace?

**Comment by mwettach** [comment]
System.IO.IOException was unhandled
  IsTransient=false
  Message=The parameter is incorrect.

  Source=mscorlib
  StackTrace:
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.BeginWriteCore(Byte[] bytes, Int32 offset, Int32 numBytes, AsyncCallback userCallback, Object stateObject)
       at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
       at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
       at WiiDeviceLibrary.Bluetooth.MsHid.MsHidStream.WriteHidReport(Byte[] writeBuffer, Int32 offset, Int32 count) in c:\Privat\Wii\wiidevicelibrary-master\WiiDeviceLibrary\Bluetooth\MsHid\MsHidStream.cs:line 97
       at WiiDeviceLibrary.Bluetooth.MsHid.MsHidStream.WriteHidReport() in c:\Privat\Wii\wiidevicelibrary-master\WiiDeviceLibrary\Bluetooth\MsHid\MsHidStream.cs:line 92
       at WiiDeviceLibrary.Bluetooth.MsHid.MsHidStream.Write(Byte[] buffer, Int32 offset, Int32 count) in c:\Privat\Wii\wiidevicelibrary-master\WiiDeviceLibrary\Bluetooth\MsHid\MsHidStream.cs:line 86
       at WiiDeviceLibrary.ReportDevice.WriteReport(Byte[] buffer, Int32 offset, Int32 count) in c:\Privat\Wii\wiidevicelibrary-master\WiiDeviceLibrary\Interface\ReportDevice.cs:line 369
       at WiiDeviceLibrary.ReportDevice.SendReport(Byte[] report) in c:\Privat\Wii\wiidevicelibrary-master\WiiDeviceLibrary\Interface\ReportDevice.cs:line 364
       at WiiDeviceLibrary.ReportDevice.SendReport() in c:\Privat\Wii\wiidevicelibrary-master\WiiDeviceLibrary\Interface\ReportDevice.cs:line 358
       at WiiDeviceLibrary.ReportWiimote.SendReport() in c:\Privat\Wii\wiidevicelibrary-master\WiiDeviceLibrary\Interface\ReportWiimote.cs:line 166
       at WiiDeviceLibrary.ReportDevice.SendAndReturnReport(InputReport returnReportType, TimeSpan timeout) in c:\Privat\Wii\wiidevicelibrary-master\WiiDeviceLibrary\Interface\ReportDevice.cs:line 393
       at WiiDeviceLibrary.ReportDevice.SendAndReturnReport(InputReport returnReportType) in c:\Privat\Wii\wiidevicelibrary-master\WiiDeviceLibrary\Interface\ReportDevice.cs:line 385
       at WiiDeviceLibrary.ReportDevice.UpdateStatus() in c:\Privat\Wii\wiidevicelibrary-master\WiiDeviceLibrary\Interface\ReportDevice.cs:line 127
       at WiiDeviceLibrary.ReportWiimote.Initialize() in c:\Privat\Wii\wiidevicelibrary-master\WiiDeviceLibrary\Interface\ReportWiimote.cs:line 140
       at WiiDeviceLibrary.Bluetooth.MsHid.MsHidDeviceProviderHelper.TryConnect(ReportDevice device, Stream deviceStream, String devicePath, SafeFileHandle fileHandle) in c:\Privat\Wii\wiidevicelibrary-master\WiiDeviceLibrary\Bluetooth\MsHid\MsHidDeviceProviderHelper.cs:line 78
       at WiiDeviceLibrary.Bluetooth.Bluesoleil.BluesoleilDeviceProvider.Connect(IDeviceInfo deviceInfo) in c:\Privat\Wii\wiidevicelibrary-master\WiiDeviceLibrary\Bluetooth\Bluesoleil\BluesoleilDeviceProvider.cs:line 214
       at Examples.ConnectExample.deviceProvider_DeviceFound(Object sender, DeviceInfoEventArgs e) in c:\Privat\Wii\wiidevicelibrary-master\Examples\ConnectExample.cs:line 69
       at WiiDeviceLibrary.Bluetooth.Bluesoleil.BluesoleilDeviceProvider.OnDeviceFound(DeviceInfoEventArgs e) in c:\Privat\Wii\wiidevicelibrary-master\WiiDeviceLibrary\Bluetooth\Bluesoleil\BluesoleilDeviceProvider.cs:line 320
       at WiiDeviceLibrary.Bluetooth.Bluesoleil.BluesoleilDeviceProvider.OnDeviceFound(BluesoleilDeviceInfo deviceInfo) in c:\Privat\Wii\wiidevicelibrary-master\WiiDeviceLibrary\Bluetooth\Bluesoleil\BluesoleilDeviceProvider.cs:line 285
       at WiiDeviceLibrary.Bluetooth.Bluesoleil.BluesoleilDeviceProvider.Discovering() in c:\Privat\Wii\wiidevicelibrary-master\WiiDeviceLibrary\Bluetooth\Bluesoleil\BluesoleilDeviceProvider.cs:line 165
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

WriteHidReport(byte[] writeBuffer = ([0] = 21, [1 - 21] = 0), int offset = 0, int count = 22)

**Comment by FrozenCow** [comment]
Hmm, not sure why that would fail. It seems correct. I would think this isn't a 64 vs 32 bit issue, since we're just using FileStream from .NET. It probably has something to do with the count, though I have no idea why that would've been changed for BlueSoleil. I know I initially had problems finding the right count too.

**Comment by mwettach** [comment]
Which version of BlueSoleil did you use with this count?

**Comment by FrozenCow** [comment]
It was a long time ago (6 or 7 years ago), so I have no idea anymore. It's been a while since I last tried BlueSoleil, but at moment I don't have a setup where I can test this. I'm afraid this can only be solved through trail-and-error.

As an alternative, you can check why MsBluetooth does not find your Wiimote by adding a breakpoint here: https://github.com/FrozenCow/wiidevicelibrary/blob/master/WiiDeviceLibrary/Bluetooth/MsBluetooth/MsBluetoothDeviceProvider.cs#L136
You can inspect the deviceInfo there. If it touches that line, it might be a good idea to take a look at: https://github.com/FrozenCow/wiidevicelibrary/blob/master/WiiDeviceLibrary/Bluetooth/MsBluetooth/MsBluetoothDeviceProvider.cs#L75-L82

**Comment by mwettach** [comment]
I played a while with it but nothing helps. BlueSoleil had the exception and MsBluetooth found nothing.

Now I uninstalled BlueSoleil and it works with MsBluetooth. I have no idea why. But it's indifferent. It works :)

Thx for your help.

**Comment by FrozenCow** [comment]
Ah, that's at least good to know. The microsoft stack has some trouble with drivers being installed that sometimes conflict with other devices, so maybe the problem lies there. Maybe uninstalling the Wii HID device from your computer and reinstalling it again was everything that was needed.

Anyway, thanks for the response. I'll close this one. Reopen when needed.
